info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-19T07:25:21.541Z"}
info: Connected to the database. {"timestamp":"2022-05-19T07:25:25.920Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-19T07:26:07.009Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-19T07:26:14.045Z"}
info: Connected to the database. {"timestamp":"2022-05-19T07:26:21.892Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-19T07:27:52.605Z"}
info: Connected to the database. {"timestamp":"2022-05-19T07:27:56.916Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-19T07:31:47.255Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-19T07:31:54.585Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-19T07:31:58.353Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-19T07:32:03.524Z"}
info: Connected to the database. {"timestamp":"2022-05-19T07:32:07.486Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-19T07:36:23.874Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-19T07:36:26.881Z"}
info: Connected to the database. {"timestamp":"2022-05-19T07:36:30.136Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-19T07:36:34.220Z"}
info: Connected to the database. {"timestamp":"2022-05-19T07:36:38.023Z"}
error: 
    status - 500 
    message - ValidationError: "name" is required 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2022-05-19T07:37:09.597Z"}
error: 
    status - 500 
    message - ValidationError: "name" is required 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2022-05-19T07:46:44.333Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-19T07:47:08.207Z"}
info: Connected to the database. {"timestamp":"2022-05-19T07:47:11.772Z"}
error: 
    status - 500 
    message - ValidationError: "name" is required 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2022-05-19T07:47:35.737Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-19T08:04:41.028Z"}
info: Connected to the database. {"timestamp":"2022-05-19T08:04:45.652Z"}
error: 
    status - 500 
    message - SyntaxError: Unexpected token } in JSON at position 36
    at JSON.parse (<anonymous>)
    at parse (D:\projectt\fundo-notes\node_modules\body-parser\lib\types\json.js:89:19)
    at D:\projectt\fundo-notes\node_modules\body-parser\lib\read.js:128:18
    at AsyncResource.runInAsyncScope (node:async_hooks:201:9)
    at invokeCallback (D:\projectt\fundo-notes\node_modules\raw-body\index.js:231:16)
    at done (D:\projectt\fundo-notes\node_modules\raw-body\index.js:220:7)
    at IncomingMessage.onEnd (D:\projectt\fundo-notes\node_modules\raw-body\index.js:280:7)
    at IncomingMessage.emit (node:events:538:35)
    at IncomingMessage.emit (node:domain:475:12)
    at endReadableNT (node:internal/streams/readable:1345:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2022-05-19T08:05:02.068Z"}
error: 
    status - 500 
    message - ValidationError: "name" is required 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2022-05-19T08:05:11.552Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-19T08:07:59.646Z"}
info: Connected to the database. {"timestamp":"2022-05-19T08:08:04.311Z"}
error: 
    status - 500 
    message - ValidationError: "name" is required 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2022-05-19T08:08:40.547Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-19T08:10:22.765Z"}
info: Connected to the database. {"timestamp":"2022-05-19T08:10:27.975Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-19T08:10:41.358Z"}
info: Connected to the database. {"timestamp":"2022-05-19T08:10:45.895Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-19T08:12:50.688Z"}
info: Connected to the database. {"timestamp":"2022-05-19T08:12:55.941Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-19T08:15:19.697Z"}
info: Connected to the database. {"timestamp":"2022-05-19T08:15:23.703Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-19T08:15:29.369Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-19T08:15:33.132Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-19T08:15:43.805Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-19T08:16:38.092Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-19T08:16:43.658Z"}
info: Connected to the database. {"timestamp":"2022-05-19T08:16:48.458Z"}
error: 
    status - 500 
    message - ValidationError: "name" is required 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2022-05-19T08:17:09.733Z"}
error: 
    status - 500 
    message - ValidationError: "name" is required 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2022-05-19T08:17:22.170Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-19T08:17:36.852Z"}
info: Connected to the database. {"timestamp":"2022-05-19T08:17:40.610Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-19T08:19:22.478Z"}
info: Connected to the database. {"timestamp":"2022-05-19T08:19:28.746Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-19T08:19:41.189Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-19T08:19:44.851Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-19T08:19:49.252Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-19T08:22:39.526Z"}
info: Connected to the database. {"timestamp":"2022-05-19T08:22:44.017Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-19T08:22:54.313Z"}
info: Connected to the database. {"timestamp":"2022-05-19T08:22:59.990Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-19T08:23:02.846Z"}
info: Connected to the database. {"timestamp":"2022-05-19T08:23:06.569Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-19T08:23:15.882Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-19T08:23:27.256Z"}
info: Connected to the database. {"timestamp":"2022-05-19T08:23:31.630Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-19T08:23:42.714Z"}
info: Connected to the database. {"timestamp":"2022-05-19T08:23:46.995Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-19T08:23:59.309Z"}
info: Connected to the database. {"timestamp":"2022-05-19T08:24:03.377Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-19T08:24:08.276Z"}
info: Connected to the database. {"timestamp":"2022-05-19T08:24:11.920Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-19T08:24:15.055Z"}
info: Connected to the database. {"timestamp":"2022-05-19T08:24:19.966Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-19T08:24:27.452Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-19T08:24:35.997Z"}
info: Connected to the database. {"timestamp":"2022-05-19T08:24:40.135Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-19T08:24:56.435Z"}
info: Connected to the database. {"timestamp":"2022-05-19T08:25:01.951Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-19T08:25:12.578Z"}
info: Connected to the database. {"timestamp":"2022-05-19T08:25:16.695Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-19T08:25:29.550Z"}
info: Connected to the database. {"timestamp":"2022-05-19T08:25:33.795Z"}
error: 
    status - 500 
    message - ValidationError: "name" is required 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2022-05-19T08:26:33.579Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-19T08:26:51.353Z"}
info: Connected to the database. {"timestamp":"2022-05-19T08:26:55.475Z"}
error: 
    status - 500 
    message - ValidationError: "name" is required 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2022-05-19T08:27:19.026Z"}
error: 
    status - 500 
    message - ValidationError: "name" is required 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2022-05-19T08:27:33.509Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-19T08:27:45.260Z"}
info: Connected to the database. {"timestamp":"2022-05-19T08:27:49.885Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-19T08:28:02.628Z"}
info: Connected to the database. {"timestamp":"2022-05-19T08:28:06.577Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-19T08:52:37.910Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-19T08:52:40.446Z"}
info: Connected to the database. {"timestamp":"2022-05-19T08:52:43.989Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-19T08:52:49.989Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-19T08:52:55.356Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-19T08:52:59.937Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-19T08:53:05.721Z"}
info: Connected to the database. {"timestamp":"2022-05-19T08:53:08.974Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-19T08:53:14.227Z"}
info: Connected to the database. {"timestamp":"2022-05-19T08:53:18.191Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-19T08:54:32.518Z"}
info: Connected to the database. {"timestamp":"2022-05-19T08:54:35.776Z"}
error: 
    status - 500 
    message - ValidationError: "name" is required 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2022-05-19T08:58:14.651Z"}
error: 
    status - 500 
    message - ValidationError: "name" is required 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2022-05-19T09:04:21.440Z"}
error: 
    status - 500 
    message - ValidationError: "name" is required 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2022-05-19T09:04:22.904Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-19T09:10:07.851Z"}
info: Connected to the database. {"timestamp":"2022-05-19T09:10:12.041Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-19T11:27:14.379Z"}
info: Connected to the database. {"timestamp":"2022-05-19T11:27:14.399Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-19T11:27:25.602Z"}
info: Connected to the database. {"timestamp":"2022-05-19T11:27:25.636Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-19T11:40:02.923Z"}
info: Connected to the database. {"timestamp":"2022-05-19T11:40:02.948Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-19T11:41:04.493Z"}
info: Connected to the database. {"timestamp":"2022-05-19T11:41:04.516Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-19T11:47:47.206Z"}
info: Connected to the database. {"timestamp":"2022-05-19T11:47:47.233Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-19T11:47:53.041Z"}
info: Connected to the database. {"timestamp":"2022-05-19T11:47:53.065Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-19T11:48:31.336Z"}
info: Connected to the database. {"timestamp":"2022-05-19T11:48:31.367Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-19T11:49:43.220Z"}
info: Connected to the database. {"timestamp":"2022-05-19T11:49:43.260Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-19T11:50:29.441Z"}
info: Connected to the database. {"timestamp":"2022-05-19T11:50:29.483Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-19T11:50:37.426Z"}
info: Connected to the database. {"timestamp":"2022-05-19T11:50:37.460Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-19T11:50:56.470Z"}
info: Connected to the database. {"timestamp":"2022-05-19T11:50:56.499Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-19T11:51:03.137Z"}
info: Connected to the database. {"timestamp":"2022-05-19T11:51:03.173Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-19T11:51:10.511Z"}
info: Connected to the database. {"timestamp":"2022-05-19T11:51:10.548Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-19T11:51:16.199Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-19T11:51:19.052Z"}
info: Connected to the database. {"timestamp":"2022-05-19T11:51:19.091Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-19T11:51:40.001Z"}
info: Connected to the database. {"timestamp":"2022-05-19T11:51:40.026Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-19T11:51:49.476Z"}
info: Connected to the database. {"timestamp":"2022-05-19T11:51:49.510Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-19T11:52:13.485Z"}
info: Connected to the database. {"timestamp":"2022-05-19T11:52:13.518Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-19T11:52:16.867Z"}
info: Connected to the database. {"timestamp":"2022-05-19T11:52:16.902Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-19T11:52:22.335Z"}
info: Connected to the database. {"timestamp":"2022-05-19T11:52:22.366Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-19T11:52:37.885Z"}
info: Connected to the database. {"timestamp":"2022-05-19T11:52:37.913Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-19T11:52:42.205Z"}
info: Connected to the database. {"timestamp":"2022-05-19T11:52:42.239Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-19T11:53:00.253Z"}
info: Connected to the database. {"timestamp":"2022-05-19T11:53:00.281Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-19T11:53:10.346Z"}
info: Connected to the database. {"timestamp":"2022-05-19T11:53:10.377Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-19T11:54:30.786Z"}
info: Connected to the database. {"timestamp":"2022-05-19T11:54:30.823Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-19T11:54:36.862Z"}
info: Connected to the database. {"timestamp":"2022-05-19T11:54:36.891Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-19T11:54:40.382Z"}
info: Connected to the database. {"timestamp":"2022-05-19T11:54:40.411Z"}
error: 
    status - 500 
    message - ValidationError: "firstname" is required 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2022-05-19T11:59:52.734Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-19T12:00:57.542Z"}
info: Connected to the database. {"timestamp":"2022-05-19T12:00:57.576Z"}
error: 
      status - 11000
      message - E11000 duplicate key error collection: SampleDB_Adesh.users index: email_1 dup key: { email: "barbade123@gmail.com" } 
      url - /api/v1/users 
      method - POST 
      IP - ::1
     {"timestamp":"2022-05-19T12:01:01.981Z"}
error: 
    status - 500 
    message - RangeError: Invalid status code: 11000
    at new NodeError (node:internal/errors:371:5)
    at ServerResponse.writeHead (node:_http_server:274:11)
    at ServerResponse.writeHead (D:\projectt\fundo-notes\node_modules\on-headers\index.js:44:26)
    at ServerResponse._implicitHeader (node:_http_server:265:8)
    at write_ (node:_http_outgoing:766:9)
    at ServerResponse.end (node:_http_outgoing:855:5)
    at ServerResponse.send (D:\projectt\fundo-notes\node_modules\express\lib\response.js:232:10)
    at ServerResponse.json (D:\projectt\fundo-notes\node_modules\express\lib\response.js:278:15)
    at appErrorHandler (D:\projectt\fundo-notes\src\middlewares\/error.middleware.js:36:26)
    at Layer.handle_error (D:\projectt\fundo-notes\node_modules\express\lib\router\layer.js:71:5)
    at trim_prefix (D:\projectt\fundo-notes\node_modules\express\lib\router\index.js:326:13)
    at D:\projectt\fundo-notes\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\projectt\fundo-notes\node_modules\express\lib\router\index.js:346:12)
    at Immediate.next (D:\projectt\fundo-notes\node_modules\express\lib\router\index.js:280:10)
    at Immediate._onImmediate (D:\projectt\fundo-notes\node_modules\express\lib\router\index.js:646:15)
    at processImmediate (node:internal/timers:468:21) 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2022-05-19T12:01:01.990Z"}
error: 
    status - 500 
    message - TypeError: UserService.userLogIn is not a function
    at _callee2$ (D:\projectt\fundo-notes\src\controllers\/user.controller.js:31:36)
    at tryCatch (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at userLogIn (D:\projectt\fundo-notes\src\controllers\/user.controller.js:29:24)
    at Layer.handle [as handle_request] (D:\projectt\fundo-notes\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\projectt\fundo-notes\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (D:\projectt\fundo-notes\node_modules\express\lib\router\route.js:114:3)
    at Layer.handle [as handle_request] (D:\projectt\fundo-notes\node_modules\express\lib\router\layer.js:95:5)
    at D:\projectt\fundo-notes\node_modules\express\lib\router\index.js:284:15
    at Function.process_params (D:\projectt\fundo-notes\node_modules\express\lib\router\index.js:346:12) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2022-05-19T12:13:26.598Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-19T12:18:03.251Z"}
info: Connected to the database. {"timestamp":"2022-05-19T12:18:03.285Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-19T12:42:47.938Z"}
info: Connected to the database. {"timestamp":"2022-05-19T12:42:47.969Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-19T12:59:45.438Z"}
info: Connected to the database. {"timestamp":"2022-05-19T12:59:45.461Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-19T13:00:24.068Z"}
info: Connected to the database. {"timestamp":"2022-05-19T13:00:24.099Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-19T13:09:57.186Z"}
info: Connected to the database. {"timestamp":"2022-05-19T13:09:57.217Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-19T13:10:54.432Z"}
info: Connected to the database. {"timestamp":"2022-05-19T13:10:54.457Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-19T13:10:57.557Z"}
info: Connected to the database. {"timestamp":"2022-05-19T13:10:57.587Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-19T13:11:06.087Z"}
info: Connected to the database. {"timestamp":"2022-05-19T13:11:06.114Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-19T13:11:09.740Z"}
info: Connected to the database. {"timestamp":"2022-05-19T13:11:09.761Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-19T13:11:15.333Z"}
info: Connected to the database. {"timestamp":"2022-05-19T13:11:15.358Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-19T13:12:21.176Z"}
info: Connected to the database. {"timestamp":"2022-05-19T13:12:21.200Z"}
error: 
    status - 500 
    message - ReferenceError: bcrypt is not defined
    at _callee2$ (D:\projectt\fundo-notes\src\services\/user.service.js:28:10)
    at tryCatch (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2022-05-19T13:13:58.145Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-19T13:14:54.084Z"}
info: Connected to the database. {"timestamp":"2022-05-19T13:14:54.109Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-19T13:14:59.994Z"}
info: Connected to the database. {"timestamp":"2022-05-19T13:15:00.023Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-19T13:15:06.624Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-19T13:15:09.208Z"}
info: Connected to the database. {"timestamp":"2022-05-19T13:15:09.241Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-19T13:34:42.390Z"}
info: Connected to the database. {"timestamp":"2022-05-19T13:34:42.412Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-19T13:42:12.551Z"}
info: Connected to the database. {"timestamp":"2022-05-19T13:42:12.589Z"}
error: 
    status - 500 
    message - TypeError: UserService.userLogIn is not a function
    at _callee2$ (D:\projectt\fundo-notes\src\controllers\/user.controller.js:31:36)
    at tryCatch (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at userLogIn (D:\projectt\fundo-notes\src\controllers\/user.controller.js:29:24)
    at Layer.handle [as handle_request] (D:\projectt\fundo-notes\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\projectt\fundo-notes\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (D:\projectt\fundo-notes\node_modules\express\lib\router\route.js:114:3)
    at Layer.handle [as handle_request] (D:\projectt\fundo-notes\node_modules\express\lib\router\layer.js:95:5)
    at D:\projectt\fundo-notes\node_modules\express\lib\router\index.js:284:15
    at Function.process_params (D:\projectt\fundo-notes\node_modules\express\lib\router\index.js:346:12) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2022-05-19T13:45:56.589Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-19T13:55:18.328Z"}
info: Connected to the database. {"timestamp":"2022-05-19T13:55:18.367Z"}
error: 
    status - 500 
    message - Error: User not Registered
    at _callee$ (D:\projectt\fundo-notes\src\services\/user.service.js:21:9)
    at tryCatch (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1//users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2022-05-19T13:55:34.700Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-19T13:56:02.946Z"}
info: Connected to the database. {"timestamp":"2022-05-19T13:56:02.966Z"}
error: 
    status - 500 
    message - ReferenceError: bcrypt is not defined
    at _callee$ (D:\projectt\fundo-notes\src\services\/user.service.js:9:10)
    at tryCatch (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1//users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2022-05-19T13:56:35.038Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-19T13:57:30.073Z"}
info: Connected to the database. {"timestamp":"2022-05-19T13:57:30.107Z"}
error: 
    status - 500 
    message - ReferenceError: bcrypt is not defined
    at _callee2$ (D:\projectt\fundo-notes\src\services\/user.service.js:24:10)
    at tryCatch (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2022-05-19T13:57:54.373Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-19T13:59:21.379Z"}
info: Connected to the database. {"timestamp":"2022-05-19T13:59:21.412Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-19T13:59:34.927Z"}
info: Connected to the database. {"timestamp":"2022-05-19T13:59:34.957Z"}
error: 
    status - 500 
    message - ReferenceError: bcrypt is not defined
    at _callee2$ (D:\projectt\fundo-notes\src\services\/user.service.js:24:10)
    at tryCatch (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2022-05-19T13:59:43.101Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-19T14:00:13.744Z"}
info: Connected to the database. {"timestamp":"2022-05-19T14:00:13.776Z"}
error: 
    status - 500 
    message - ReferenceError: bcrypt is not defined
    at _callee2$ (D:\projectt\fundo-notes\src\services\/user.service.js:24:10)
    at tryCatch (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2022-05-19T14:00:27.363Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-19T14:00:50.861Z"}
info: Connected to the database. {"timestamp":"2022-05-19T14:00:50.893Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-19T14:00:56.412Z"}
info: Connected to the database. {"timestamp":"2022-05-19T14:00:56.445Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-19T14:01:02.245Z"}
info: Connected to the database. {"timestamp":"2022-05-19T14:01:02.276Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-19T14:02:32.523Z"}
info: Connected to the database. {"timestamp":"2022-05-19T14:02:32.556Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-19T14:02:38.362Z"}
info: Connected to the database. {"timestamp":"2022-05-19T14:02:38.388Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-19T14:03:00.819Z"}
info: Connected to the database. {"timestamp":"2022-05-19T14:03:00.849Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-19T14:03:20.129Z"}
info: Connected to the database. {"timestamp":"2022-05-19T14:03:20.157Z"}
error: 
    status - 500 
    message - TypeError: UserService.userLogIn is not a function
    at _callee2$ (D:\projectt\fundo-notes\src\controllers\/user.controller.js:31:36)
    at tryCatch (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at userLogIn (D:\projectt\fundo-notes\src\controllers\/user.controller.js:29:24)
    at Layer.handle [as handle_request] (D:\projectt\fundo-notes\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\projectt\fundo-notes\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (D:\projectt\fundo-notes\node_modules\express\lib\router\route.js:114:3)
    at Layer.handle [as handle_request] (D:\projectt\fundo-notes\node_modules\express\lib\router\layer.js:95:5)
    at D:\projectt\fundo-notes\node_modules\express\lib\router\index.js:284:15
    at Function.process_params (D:\projectt\fundo-notes\node_modules\express\lib\router\index.js:346:12) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2022-05-19T14:04:07.653Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-19T14:04:55.247Z"}
info: Connected to the database. {"timestamp":"2022-05-19T14:04:55.271Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-19T14:06:59.624Z"}
info: Connected to the database. {"timestamp":"2022-05-19T14:06:59.669Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-19T14:17:46.218Z"}
info: Connected to the database. {"timestamp":"2022-05-19T14:17:46.249Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-19T14:18:00.375Z"}
info: Connected to the database. {"timestamp":"2022-05-19T14:18:00.399Z"}
error: 
    status - 500 
    message - ReferenceError: user is not defined
    at _callee$ (D:\projectt\fundo-notes\src\services\/user.service.js:5:26)
    at tryCatch (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.userLogIn (D:\projectt\fundo-notes\src\services\/user.service.js:5:23)
    at _callee2$ (D:\projectt\fundo-notes\src\controllers\/user.controller.js:31:36)
    at tryCatch (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2022-05-19T14:18:18.725Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-19T14:18:36.452Z"}
info: Connected to the database. {"timestamp":"2022-05-19T14:18:36.476Z"}
error: 
    status - 500 
    message - ReferenceError: user is not defined
    at _callee$ (D:\projectt\fundo-notes\src\services\/user.service.js:5:26)
    at tryCatch (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.userLogIn (D:\projectt\fundo-notes\src\services\/user.service.js:5:23)
    at _callee2$ (D:\projectt\fundo-notes\src\controllers\/user.controller.js:31:36)
    at tryCatch (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2022-05-19T14:18:40.678Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-19T14:19:44.620Z"}
info: Connected to the database. {"timestamp":"2022-05-19T14:19:44.644Z"}
error: 
    status - 500 
    message - ReferenceError: user is not defined
    at _callee$ (D:\projectt\fundo-notes\src\services\/user.service.js:5:26)
    at tryCatch (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.userLogIn (D:\projectt\fundo-notes\src\services\/user.service.js:5:23)
    at _callee2$ (D:\projectt\fundo-notes\src\controllers\/user.controller.js:31:36)
    at tryCatch (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2022-05-19T14:20:56.399Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-19T14:22:44.231Z"}
info: Connected to the database. {"timestamp":"2022-05-19T14:22:44.253Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-19T14:28:51.849Z"}
info: Connected to the database. {"timestamp":"2022-05-19T14:28:51.882Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-19T14:30:32.965Z"}
info: Connected to the database. {"timestamp":"2022-05-19T14:30:32.994Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-19T14:30:40.798Z"}
info: Connected to the database. {"timestamp":"2022-05-19T14:30:40.922Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-19T14:30:44.576Z"}
info: Connected to the database. {"timestamp":"2022-05-19T14:30:44.606Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-19T14:33:00.168Z"}
info: Connected to the database. {"timestamp":"2022-05-19T14:33:00.201Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-19T14:33:06.669Z"}
info: Connected to the database. {"timestamp":"2022-05-19T14:33:06.700Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-19T14:33:30.884Z"}
info: Connected to the database. {"timestamp":"2022-05-19T14:33:30.919Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-19T14:33:43.770Z"}
info: Connected to the database. {"timestamp":"2022-05-19T14:33:43.798Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-19T14:33:52.501Z"}
info: Connected to the database. {"timestamp":"2022-05-19T14:33:52.527Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-19T14:33:56.061Z"}
info: Connected to the database. {"timestamp":"2022-05-19T14:33:56.089Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-19T14:34:03.325Z"}
info: Connected to the database. {"timestamp":"2022-05-19T14:34:03.355Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-19T14:34:15.111Z"}
info: Connected to the database. {"timestamp":"2022-05-19T14:34:15.148Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-19T14:38:59.415Z"}
info: Connected to the database. {"timestamp":"2022-05-19T14:38:59.448Z"}
error: 
    status - 500 
    message - TypeError: UserService.getAllUsers is not a function
    at _callee$ (D:\projectt\fundo-notes\src\controllers\/user.controller.js:12:36)
    at tryCatch (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at getAllUsers (D:\projectt\fundo-notes\src\controllers\/user.controller.js:10:25)
    at Layer.handle [as handle_request] (D:\projectt\fundo-notes\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\projectt\fundo-notes\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (D:\projectt\fundo-notes\node_modules\express\lib\router\route.js:114:3)
    at Layer.handle [as handle_request] (D:\projectt\fundo-notes\node_modules\express\lib\router\layer.js:95:5)
    at D:\projectt\fundo-notes\node_modules\express\lib\router\index.js:284:15
    at Function.process_params (D:\projectt\fundo-notes\node_modules\express\lib\router\index.js:346:12) 
    url - /api/v1/users/alldata 
    method - GET 
    IP - ::1
   {"timestamp":"2022-05-19T14:39:51.962Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-19T14:40:25.828Z"}
info: Connected to the database. {"timestamp":"2022-05-19T14:40:25.857Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-19T14:41:16.895Z"}
info: Connected to the database. {"timestamp":"2022-05-19T14:41:16.919Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-19T14:43:12.299Z"}
info: Connected to the database. {"timestamp":"2022-05-19T14:43:12.330Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-19T14:48:06.105Z"}
info: Connected to the database. {"timestamp":"2022-05-19T14:48:06.128Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-19T14:48:10.579Z"}
info: Connected to the database. {"timestamp":"2022-05-19T14:48:10.607Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-19T14:50:31.739Z"}
info: Connected to the database. {"timestamp":"2022-05-19T14:50:31.765Z"}
error: 
    status - 500 
    message - ReferenceError: userBody is not defined
    at _callee2$ (D:\projectt\fundo-notes\src\services\/user.service.js:11:45)
    at tryCatch (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.userLogIn (D:\projectt\fundo-notes\src\services\/user.service.js:10:25)
    at _callee3$ (D:\projectt\fundo-notes\src\controllers\/user.controller.js:49:36)
    at tryCatch (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2022-05-19T14:50:48.179Z"}
error: 
    status - 500 
    message - ReferenceError: userBody is not defined
    at _callee2$ (D:\projectt\fundo-notes\src\services\/user.service.js:11:45)
    at tryCatch (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.userLogIn (D:\projectt\fundo-notes\src\services\/user.service.js:10:25)
    at _callee3$ (D:\projectt\fundo-notes\src\controllers\/user.controller.js:49:36)
    at tryCatch (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2022-05-19T14:51:01.573Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-19T14:51:59.079Z"}
info: Connected to the database. {"timestamp":"2022-05-19T14:51:59.105Z"}
error: 
    status - 500 
    message - ReferenceError: userBody is not defined
    at _callee2$ (D:\projectt\fundo-notes\src\services\/user.service.js:11:45)
    at tryCatch (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.userLogIn (D:\projectt\fundo-notes\src\services\/user.service.js:10:25)
    at _callee3$ (D:\projectt\fundo-notes\src\controllers\/user.controller.js:49:36)
    at tryCatch (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2022-05-19T14:52:16.391Z"}
error: 
    status - 500 
    message - ReferenceError: userBody is not defined
    at _callee2$ (D:\projectt\fundo-notes\src\services\/user.service.js:11:45)
    at tryCatch (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.userLogIn (D:\projectt\fundo-notes\src\services\/user.service.js:10:25)
    at _callee3$ (D:\projectt\fundo-notes\src\controllers\/user.controller.js:49:36)
    at tryCatch (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2022-05-19T14:52:17.991Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-19T14:52:37.267Z"}
info: Connected to the database. {"timestamp":"2022-05-19T14:52:37.292Z"}
error: 
    status - 500 
    message - ReferenceError: userBody is not defined
    at _callee2$ (D:\projectt\fundo-notes\src\services\/user.service.js:11:45)
    at tryCatch (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.userLogIn (D:\projectt\fundo-notes\src\services\/user.service.js:10:25)
    at _callee3$ (D:\projectt\fundo-notes\src\controllers\/user.controller.js:49:36)
    at tryCatch (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/users 
    method - GET 
    IP - ::1
   {"timestamp":"2022-05-19T14:52:47.201Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-19T14:53:15.174Z"}
info: Connected to the database. {"timestamp":"2022-05-19T14:53:15.195Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-19T14:53:36.264Z"}
info: Connected to the database. {"timestamp":"2022-05-19T14:53:36.295Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-19T14:53:41.641Z"}
info: Connected to the database. {"timestamp":"2022-05-19T14:53:41.668Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-19T14:54:11.352Z"}
info: Connected to the database. {"timestamp":"2022-05-19T14:54:11.379Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-19T14:54:14.276Z"}
info: Connected to the database. {"timestamp":"2022-05-19T14:54:14.308Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-19T14:54:17.997Z"}
info: Connected to the database. {"timestamp":"2022-05-19T14:54:18.038Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-19T14:54:24.256Z"}
info: Connected to the database. {"timestamp":"2022-05-19T14:54:24.290Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T01:49:02.226Z"}
info: Connected to the database. {"timestamp":"2022-05-20T01:49:02.249Z"}
error: 
    status - 500 
    message - ReferenceError: body is not defined
    at _callee2$ (D:\projectt\fundo-notes\src\services\/user.service.js:11:34)
    at tryCatch (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.userLogIn (D:\projectt\fundo-notes\src\services\/user.service.js:10:25)
    at _callee3$ (D:\projectt\fundo-notes\src\controllers\/user.controller.js:49:36)
    at tryCatch (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2022-05-20T01:49:52.768Z"}
error: 
    status - 500 
    message - ReferenceError: body is not defined
    at _callee2$ (D:\projectt\fundo-notes\src\services\/user.service.js:11:34)
    at tryCatch (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.userLogIn (D:\projectt\fundo-notes\src\services\/user.service.js:10:25)
    at _callee3$ (D:\projectt\fundo-notes\src\controllers\/user.controller.js:49:36)
    at tryCatch (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2022-05-20T01:50:04.962Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T01:50:52.271Z"}
info: Connected to the database. {"timestamp":"2022-05-20T01:50:52.289Z"}
error: 
    status - 500 
    message - ReferenceError: body is not defined
    at _callee2$ (D:\projectt\fundo-notes\src\services\/user.service.js:11:34)
    at tryCatch (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.userLogIn (D:\projectt\fundo-notes\src\services\/user.service.js:10:25)
    at _callee3$ (D:\projectt\fundo-notes\src\controllers\/user.controller.js:49:36)
    at tryCatch (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2022-05-20T01:51:57.899Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T02:31:20.216Z"}
info: Connected to the database. {"timestamp":"2022-05-20T02:31:20.238Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T03:12:02.363Z"}
info: Connected to the database. {"timestamp":"2022-05-20T03:12:02.386Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T03:12:33.935Z"}
info: Connected to the database. {"timestamp":"2022-05-20T03:12:33.966Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T04:04:56.036Z"}
info: Connected to the database. {"timestamp":"2022-05-20T04:04:56.068Z"}
error: 
    status - 500 
    message - TypeError: UserService.newUser is not a function
    at _callee2$ (D:\projectt\fundo-notes\src\controllers\/user.controller.js:30:36)
    at tryCatch (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at userRegistration (D:\projectt\fundo-notes\src\controllers\/user.controller.js:28:31)
    at Layer.handle [as handle_request] (D:\projectt\fundo-notes\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\projectt\fundo-notes\node_modules\express\lib\router\route.js:144:13)
    at userRegistrationValidator (D:\projectt\fundo-notes\src\validators\/user.validator.js:15:5)
    at Layer.handle [as handle_request] (D:\projectt\fundo-notes\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\projectt\fundo-notes\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (D:\projectt\fundo-notes\node_modules\express\lib\router\route.js:114:3) 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2022-05-20T04:06:24.629Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T04:06:42.226Z"}
info: Connected to the database. {"timestamp":"2022-05-20T04:06:42.258Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T04:11:30.051Z"}
info: Connected to the database. {"timestamp":"2022-05-20T04:11:30.084Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T04:12:20.101Z"}
info: Connected to the database. {"timestamp":"2022-05-20T04:12:20.129Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T04:12:25.881Z"}
info: Connected to the database. {"timestamp":"2022-05-20T04:12:25.916Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T04:12:37.332Z"}
info: Connected to the database. {"timestamp":"2022-05-20T04:12:37.375Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T04:12:44.553Z"}
info: Connected to the database. {"timestamp":"2022-05-20T04:12:44.592Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T04:12:54.266Z"}
info: Connected to the database. {"timestamp":"2022-05-20T04:12:54.336Z"}
error: 
      status - 11000
      message - E11000 duplicate key error collection: SampleDB_Adesh.users index: email_1 dup key: { email: "abcde@gmail.com" } 
      url - /api/v1/users 
      method - POST 
      IP - ::1
     {"timestamp":"2022-05-20T04:13:05.785Z"}
error: 
    status - 500 
    message - RangeError: Invalid status code: 11000
    at new NodeError (node:internal/errors:371:5)
    at ServerResponse.writeHead (node:_http_server:274:11)
    at ServerResponse.writeHead (D:\projectt\fundo-notes\node_modules\on-headers\index.js:44:26)
    at ServerResponse._implicitHeader (node:_http_server:265:8)
    at write_ (node:_http_outgoing:766:9)
    at ServerResponse.end (node:_http_outgoing:855:5)
    at ServerResponse.send (D:\projectt\fundo-notes\node_modules\express\lib\response.js:232:10)
    at ServerResponse.json (D:\projectt\fundo-notes\node_modules\express\lib\response.js:278:15)
    at appErrorHandler (D:\projectt\fundo-notes\src\middlewares\/error.middleware.js:36:26)
    at Layer.handle_error (D:\projectt\fundo-notes\node_modules\express\lib\router\layer.js:71:5)
    at trim_prefix (D:\projectt\fundo-notes\node_modules\express\lib\router\index.js:326:13)
    at D:\projectt\fundo-notes\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\projectt\fundo-notes\node_modules\express\lib\router\index.js:346:12)
    at Immediate.next (D:\projectt\fundo-notes\node_modules\express\lib\router\index.js:280:10)
    at Immediate._onImmediate (D:\projectt\fundo-notes\node_modules\express\lib\router\index.js:646:15)
    at processImmediate (node:internal/timers:468:21) 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2022-05-20T04:13:05.813Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T04:15:03.687Z"}
info: Connected to the database. {"timestamp":"2022-05-20T04:15:03.744Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T04:15:17.567Z"}
info: Connected to the database. {"timestamp":"2022-05-20T04:15:17.614Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T04:15:22.085Z"}
info: Connected to the database. {"timestamp":"2022-05-20T04:15:22.118Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T04:15:26.552Z"}
info: Connected to the database. {"timestamp":"2022-05-20T04:15:26.585Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T04:16:53.006Z"}
info: Connected to the database. {"timestamp":"2022-05-20T04:16:53.037Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T04:18:04.990Z"}
info: Connected to the database. {"timestamp":"2022-05-20T04:18:05.023Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T04:18:28.613Z"}
info: Connected to the database. {"timestamp":"2022-05-20T04:18:28.649Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T04:18:48.131Z"}
info: Connected to the database. {"timestamp":"2022-05-20T04:18:48.171Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T04:19:05.272Z"}
info: Connected to the database. {"timestamp":"2022-05-20T04:19:05.302Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T04:20:04.078Z"}
info: Connected to the database. {"timestamp":"2022-05-20T04:20:04.119Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T04:21:00.557Z"}
info: Connected to the database. {"timestamp":"2022-05-20T04:21:00.594Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T04:21:13.219Z"}
info: Connected to the database. {"timestamp":"2022-05-20T04:21:13.252Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T04:21:21.234Z"}
info: Connected to the database. {"timestamp":"2022-05-20T04:21:21.272Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T04:22:55.979Z"}
info: Connected to the database. {"timestamp":"2022-05-20T04:22:56.003Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T04:24:29.408Z"}
info: Connected to the database. {"timestamp":"2022-05-20T04:24:29.444Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T04:24:33.255Z"}
info: Connected to the database. {"timestamp":"2022-05-20T04:24:33.293Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T04:24:42.713Z"}
info: Connected to the database. {"timestamp":"2022-05-20T04:24:42.750Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T04:25:35.901Z"}
info: Connected to the database. {"timestamp":"2022-05-20T04:25:35.930Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T04:25:40.467Z"}
info: Connected to the database. {"timestamp":"2022-05-20T04:25:40.497Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T04:29:45.059Z"}
info: Connected to the database. {"timestamp":"2022-05-20T04:29:45.092Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T04:29:58.858Z"}
info: Connected to the database. {"timestamp":"2022-05-20T04:29:58.889Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T04:30:17.066Z"}
info: Connected to the database. {"timestamp":"2022-05-20T04:30:17.107Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T04:30:26.235Z"}
info: Connected to the database. {"timestamp":"2022-05-20T04:30:26.270Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T04:31:45.265Z"}
info: Connected to the database. {"timestamp":"2022-05-20T04:31:45.299Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T04:31:52.597Z"}
info: Connected to the database. {"timestamp":"2022-05-20T04:31:52.626Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T04:32:05.949Z"}
info: Connected to the database. {"timestamp":"2022-05-20T04:32:05.982Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T04:32:11.475Z"}
info: Connected to the database. {"timestamp":"2022-05-20T04:32:11.508Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T04:32:51.150Z"}
info: Connected to the database. {"timestamp":"2022-05-20T04:32:51.185Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T04:33:10.335Z"}
info: Connected to the database. {"timestamp":"2022-05-20T04:33:10.364Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T04:33:16.771Z"}
info: Connected to the database. {"timestamp":"2022-05-20T04:33:16.804Z"}
error: 
    status - 500 
    message - ReferenceError: saltRound is not defined
    at _callee3$ (D:\projectt\fundo-notes\src\services\/user.service.js:29:38)
    at tryCatch (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.newUser (D:\projectt\fundo-notes\src\services\/user.service.js:16:21)
    at _callee2$ (D:\projectt\fundo-notes\src\controllers\/user.controller.js:30:36)
    at tryCatch (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2022-05-20T04:33:58.944Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T04:34:34.739Z"}
info: Connected to the database. {"timestamp":"2022-05-20T04:34:34.765Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T04:34:54.992Z"}
info: Connected to the database. {"timestamp":"2022-05-20T04:34:55.017Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T04:36:00.179Z"}
info: Connected to the database. {"timestamp":"2022-05-20T04:36:00.208Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T08:13:40.420Z"}
info: Connected to the database. {"timestamp":"2022-05-20T08:13:40.447Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T08:13:46.368Z"}
info: Connected to the database. {"timestamp":"2022-05-20T08:13:46.394Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T08:13:49.172Z"}
info: Connected to the database. {"timestamp":"2022-05-20T08:13:49.202Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T08:13:56.982Z"}
info: Connected to the database. {"timestamp":"2022-05-20T08:13:57.009Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T08:39:36.262Z"}
info: Connected to the database. {"timestamp":"2022-05-20T08:39:36.287Z"}
error: 
    status - 500 
    message - ValidationError: "password" is required 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2022-05-20T08:40:54.499Z"}
error: 
    status - 500 
    message - ValidationError: "email" is required 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2022-05-20T08:41:09.883Z"}
error: 
    status - 500 
    message - ReferenceError: userBody is not defined
    at _callee2$ (D:\projectt\fundo-notes\src\services\/user.service.js:12:43)
    at tryCatch (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.userLogIn (D:\projectt\fundo-notes\src\services\/user.service.js:11:23)
    at _callee3$ (D:\projectt\fundo-notes\src\controllers\/user.controller.js:49:36)
    at tryCatch (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2022-05-20T08:41:22.501Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T08:42:14.882Z"}
info: Connected to the database. {"timestamp":"2022-05-20T08:42:14.907Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T08:42:17.241Z"}
info: Connected to the database. {"timestamp":"2022-05-20T08:42:17.262Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T08:42:58.985Z"}
info: Connected to the database. {"timestamp":"2022-05-20T08:42:59.007Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T08:43:31.494Z"}
info: Connected to the database. {"timestamp":"2022-05-20T08:43:31.521Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T08:43:35.898Z"}
info: Connected to the database. {"timestamp":"2022-05-20T08:43:35.923Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T08:43:52.658Z"}
info: Connected to the database. {"timestamp":"2022-05-20T08:43:52.681Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T08:44:12.824Z"}
info: Connected to the database. {"timestamp":"2022-05-20T08:44:12.854Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T08:44:24.350Z"}
info: Connected to the database. {"timestamp":"2022-05-20T08:44:24.374Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T08:44:29.365Z"}
info: Connected to the database. {"timestamp":"2022-05-20T08:44:29.386Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T08:45:28.942Z"}
info: Connected to the database. {"timestamp":"2022-05-20T08:45:28.977Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T08:45:35.364Z"}
info: Connected to the database. {"timestamp":"2022-05-20T08:45:35.402Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T08:45:38.002Z"}
info: Connected to the database. {"timestamp":"2022-05-20T08:45:38.029Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T08:45:44.369Z"}
info: Connected to the database. {"timestamp":"2022-05-20T08:45:44.389Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T08:45:54.844Z"}
info: Connected to the database. {"timestamp":"2022-05-20T08:45:54.869Z"}
error: 
    status - 500 
    message - ValidationError: "password" is required 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2022-05-20T08:46:05.229Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T08:47:23.353Z"}
info: Connected to the database. {"timestamp":"2022-05-20T08:47:23.380Z"}
error: 
    status - 500 
    message - ValidationError: "password" is required 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2022-05-20T08:47:27.388Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T08:47:56.444Z"}
info: Connected to the database. {"timestamp":"2022-05-20T08:47:56.475Z"}
error: 
    status - 500 
    message - ValidationError: "password" is required 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2022-05-20T08:48:00.524Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T08:48:49.800Z"}
info: Connected to the database. {"timestamp":"2022-05-20T08:48:49.824Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T08:48:53.533Z"}
info: Connected to the database. {"timestamp":"2022-05-20T08:48:53.564Z"}
error: 
    status - 500 
    message - ValidationError: "password" is required 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2022-05-20T08:48:57.191Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T08:50:45.121Z"}
info: Connected to the database. {"timestamp":"2022-05-20T08:50:45.153Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T08:51:12.430Z"}
info: Connected to the database. {"timestamp":"2022-05-20T08:51:12.461Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T08:51:26.502Z"}
info: Connected to the database. {"timestamp":"2022-05-20T08:51:26.527Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T08:51:34.065Z"}
info: Connected to the database. {"timestamp":"2022-05-20T08:51:34.091Z"}
error: 
    status - 500 
    message - ValidationError: "password" is required 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2022-05-20T08:51:51.780Z"}
error: 
    status - 500 
    message - ValidationError: "password" is required 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2022-05-20T08:51:53.304Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T08:52:45.822Z"}
info: Connected to the database. {"timestamp":"2022-05-20T08:52:45.845Z"}
error: 
    status - 500 
    message - ValidationError: "password" is required 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2022-05-20T08:53:40.038Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T08:54:11.769Z"}
info: Connected to the database. {"timestamp":"2022-05-20T08:54:11.793Z"}
error: 
    status - 500 
    message - ValidationError: "password" is required 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2022-05-20T08:54:18.852Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T08:54:27.378Z"}
info: Connected to the database. {"timestamp":"2022-05-20T08:54:27.405Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T08:54:40.249Z"}
info: Connected to the database. {"timestamp":"2022-05-20T08:54:40.274Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T08:54:48.783Z"}
info: Connected to the database. {"timestamp":"2022-05-20T08:54:48.814Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T08:54:58.469Z"}
info: Connected to the database. {"timestamp":"2022-05-20T08:54:58.504Z"}
error: 
    status - 500 
    message - ValidationError: "firstName" is required 
    url - /api/v1/users/ 
    method - POST 
    IP - ::1
   {"timestamp":"2022-05-20T08:58:09.509Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T09:07:33.711Z"}
info: Connected to the database. {"timestamp":"2022-05-20T09:07:33.748Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T09:07:39.048Z"}
info: Connected to the database. {"timestamp":"2022-05-20T09:07:39.076Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T09:09:04.752Z"}
info: Connected to the database. {"timestamp":"2022-05-20T09:09:04.776Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T09:09:23.289Z"}
info: Connected to the database. {"timestamp":"2022-05-20T09:09:23.318Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T09:09:34.105Z"}
info: Connected to the database. {"timestamp":"2022-05-20T09:09:34.137Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T09:09:40.207Z"}
info: Connected to the database. {"timestamp":"2022-05-20T09:09:40.233Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T09:11:05.404Z"}
info: Connected to the database. {"timestamp":"2022-05-20T09:11:05.429Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T12:03:35.719Z"}
info: Connected to the database. {"timestamp":"2022-05-20T12:03:35.751Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T12:03:46.917Z"}
info: Connected to the database. {"timestamp":"2022-05-20T12:03:46.948Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T12:09:41.540Z"}
info: Connected to the database. {"timestamp":"2022-05-20T12:09:41.565Z"}
error: 
    status - 500 
    message - ReferenceError: userBody is not defined
    at _callee2$ (D:\projectt\fundo-notes\src\services\/user.service.js:12:43)
    at tryCatch (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.userLogIn (D:\projectt\fundo-notes\src\services\/user.service.js:11:23)
    at _callee3$ (D:\projectt\fundo-notes\src\controllers\/user.controller.js:49:36)
    at tryCatch (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2022-05-20T12:09:58.724Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T12:10:15.758Z"}
info: Connected to the database. {"timestamp":"2022-05-20T12:10:15.789Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T12:10:20.974Z"}
info: Connected to the database. {"timestamp":"2022-05-20T12:10:21.005Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T12:10:27.492Z"}
info: Connected to the database. {"timestamp":"2022-05-20T12:10:27.521Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T12:10:34.207Z"}
info: Connected to the database. {"timestamp":"2022-05-20T12:10:34.232Z"}
error: 
    status - 500 
    message - ReferenceError: jwt is not defined
    at _callee2$ (D:\projectt\fundo-notes\src\services\/user.service.js:21:9)
    at tryCatch (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2022-05-20T12:10:51.579Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T12:16:25.691Z"}
info: Connected to the database. {"timestamp":"2022-05-20T12:16:25.722Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T12:16:48.979Z"}
info: Connected to the database. {"timestamp":"2022-05-20T12:16:49.012Z"}
error: 
    status - 500 
    message - ObjectParameterError: Parameter "filter" to findOne() must be an object, got barbade123@gmail.com
    at model.Query.Query.findOne (D:\projectt\fundo-notes\node_modules\mongoose\lib\query.js:2321:16)
    at Function.findOne (D:\projectt\fundo-notes\node_modules\mongoose\lib\model.js:2267:13)
    at _callee2$ (D:\projectt\fundo-notes\src\services\/user.service.js:12:27)
    at tryCatch (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.userLogIn (D:\projectt\fundo-notes\src\services\/user.service.js:11:23)
    at _callee3$ (D:\projectt\fundo-notes\src\controllers\/user.controller.js:49:36)
    at tryCatch (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:119:21) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2022-05-20T12:18:50.692Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T12:19:17.099Z"}
info: Connected to the database. {"timestamp":"2022-05-20T12:19:17.132Z"}
error: 
    status - 500 
    message - ReferenceError: jwt is not defined
    at _callee2$ (D:\projectt\fundo-notes\src\services\/user.service.js:21:9)
    at tryCatch (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2022-05-20T12:19:23.838Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-20T12:28:26.631Z"}
info: Connected to the database. {"timestamp":"2022-05-20T12:28:26.664Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-27T02:59:27.882Z"}
info: Connected to the database. {"timestamp":"2022-05-27T02:59:27.909Z"}
error: 
    status - 500 
    message - ValidationError: "firstName" is required 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2022-05-27T03:00:59.807Z"}
error: 
      status - 11000
      message - E11000 duplicate key error collection: SampleDB_Adesh.users index: email_1 dup key: { email: "barbade@gamil.com" } 
      url - /api/v1/users 
      method - POST 
      IP - ::1
     {"timestamp":"2022-05-27T03:10:13.923Z"}
error: 
    status - 500 
    message - RangeError: Invalid status code: 11000
    at new NodeError (node:internal/errors:371:5)
    at ServerResponse.writeHead (node:_http_server:274:11)
    at ServerResponse.writeHead (D:\projectt\fundo-notes\node_modules\on-headers\index.js:44:26)
    at ServerResponse._implicitHeader (node:_http_server:265:8)
    at write_ (node:_http_outgoing:766:9)
    at ServerResponse.end (node:_http_outgoing:855:5)
    at ServerResponse.send (D:\projectt\fundo-notes\node_modules\express\lib\response.js:232:10)
    at ServerResponse.json (D:\projectt\fundo-notes\node_modules\express\lib\response.js:278:15)
    at appErrorHandler (D:\projectt\fundo-notes\src\middlewares\/error.middleware.js:36:26)
    at Layer.handle_error (D:\projectt\fundo-notes\node_modules\express\lib\router\layer.js:71:5)
    at trim_prefix (D:\projectt\fundo-notes\node_modules\express\lib\router\index.js:326:13)
    at D:\projectt\fundo-notes\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\projectt\fundo-notes\node_modules\express\lib\router\index.js:346:12)
    at Immediate.next (D:\projectt\fundo-notes\node_modules\express\lib\router\index.js:280:10)
    at Immediate._onImmediate (D:\projectt\fundo-notes\node_modules\express\lib\router\index.js:646:15)
    at processImmediate (node:internal/timers:468:21) 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2022-05-27T03:10:13.937Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-27T03:11:55.297Z"}
info: Connected to the database. {"timestamp":"2022-05-27T03:11:55.317Z"}
error: 
      status - 11000
      message - E11000 duplicate key error collection: SampleDB_Adesh.users index: email_1 dup key: { email: "barbade@gamil.com" } 
      url - /api/v1/users 
      method - POST 
      IP - ::1
     {"timestamp":"2022-05-27T03:12:03.492Z"}
error: 
    status - 500 
    message - RangeError: Invalid status code: 11000
    at new NodeError (node:internal/errors:371:5)
    at ServerResponse.writeHead (node:_http_server:274:11)
    at ServerResponse.writeHead (D:\projectt\fundo-notes\node_modules\on-headers\index.js:44:26)
    at ServerResponse._implicitHeader (node:_http_server:265:8)
    at write_ (node:_http_outgoing:766:9)
    at ServerResponse.end (node:_http_outgoing:855:5)
    at ServerResponse.send (D:\projectt\fundo-notes\node_modules\express\lib\response.js:232:10)
    at ServerResponse.json (D:\projectt\fundo-notes\node_modules\express\lib\response.js:278:15)
    at appErrorHandler (D:\projectt\fundo-notes\src\middlewares\/error.middleware.js:36:26)
    at Layer.handle_error (D:\projectt\fundo-notes\node_modules\express\lib\router\layer.js:71:5)
    at trim_prefix (D:\projectt\fundo-notes\node_modules\express\lib\router\index.js:326:13)
    at D:\projectt\fundo-notes\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\projectt\fundo-notes\node_modules\express\lib\router\index.js:346:12)
    at Immediate.next (D:\projectt\fundo-notes\node_modules\express\lib\router\index.js:280:10)
    at Immediate._onImmediate (D:\projectt\fundo-notes\node_modules\express\lib\router\index.js:646:15)
    at processImmediate (node:internal/timers:468:21) 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2022-05-27T03:12:03.503Z"}
error: 
      status - 11000
      message - E11000 duplicate key error collection: SampleDB_Adesh.users index: email_1 dup key: { email: "barbade@gamil.com" } 
      url - /api/v1/users 
      method - POST 
      IP - ::1
     {"timestamp":"2022-05-27T03:12:59.060Z"}
error: 
    status - 500 
    message - RangeError: Invalid status code: 11000
    at new NodeError (node:internal/errors:371:5)
    at ServerResponse.writeHead (node:_http_server:274:11)
    at ServerResponse.writeHead (D:\projectt\fundo-notes\node_modules\on-headers\index.js:44:26)
    at ServerResponse._implicitHeader (node:_http_server:265:8)
    at write_ (node:_http_outgoing:766:9)
    at ServerResponse.end (node:_http_outgoing:855:5)
    at ServerResponse.send (D:\projectt\fundo-notes\node_modules\express\lib\response.js:232:10)
    at ServerResponse.json (D:\projectt\fundo-notes\node_modules\express\lib\response.js:278:15)
    at appErrorHandler (D:\projectt\fundo-notes\src\middlewares\/error.middleware.js:36:26)
    at Layer.handle_error (D:\projectt\fundo-notes\node_modules\express\lib\router\layer.js:71:5)
    at trim_prefix (D:\projectt\fundo-notes\node_modules\express\lib\router\index.js:326:13)
    at D:\projectt\fundo-notes\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\projectt\fundo-notes\node_modules\express\lib\router\index.js:346:12)
    at Immediate.next (D:\projectt\fundo-notes\node_modules\express\lib\router\index.js:280:10)
    at Immediate._onImmediate (D:\projectt\fundo-notes\node_modules\express\lib\router\index.js:646:15)
    at processImmediate (node:internal/timers:468:21) 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2022-05-27T03:12:59.067Z"}
error: 
      status - 11000
      message - E11000 duplicate key error collection: SampleDB_Adesh.users index: email_1 dup key: { email: "barbade@gamil.com" } 
      url - /api/v1/users 
      method - POST 
      IP - ::1
     {"timestamp":"2022-05-27T03:13:30.908Z"}
error: 
    status - 500 
    message - RangeError: Invalid status code: 11000
    at new NodeError (node:internal/errors:371:5)
    at ServerResponse.writeHead (node:_http_server:274:11)
    at ServerResponse.writeHead (D:\projectt\fundo-notes\node_modules\on-headers\index.js:44:26)
    at ServerResponse._implicitHeader (node:_http_server:265:8)
    at write_ (node:_http_outgoing:766:9)
    at ServerResponse.end (node:_http_outgoing:855:5)
    at ServerResponse.send (D:\projectt\fundo-notes\node_modules\express\lib\response.js:232:10)
    at ServerResponse.json (D:\projectt\fundo-notes\node_modules\express\lib\response.js:278:15)
    at appErrorHandler (D:\projectt\fundo-notes\src\middlewares\/error.middleware.js:36:26)
    at Layer.handle_error (D:\projectt\fundo-notes\node_modules\express\lib\router\layer.js:71:5)
    at trim_prefix (D:\projectt\fundo-notes\node_modules\express\lib\router\index.js:326:13)
    at D:\projectt\fundo-notes\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\projectt\fundo-notes\node_modules\express\lib\router\index.js:346:12)
    at Immediate.next (D:\projectt\fundo-notes\node_modules\express\lib\router\index.js:280:10)
    at Immediate._onImmediate (D:\projectt\fundo-notes\node_modules\express\lib\router\index.js:646:15)
    at processImmediate (node:internal/timers:468:21) 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2022-05-27T03:13:30.914Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-27T03:19:21.825Z"}
info: Connected to the database. {"timestamp":"2022-05-27T03:19:21.850Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-27T03:26:01.592Z"}
info: Connected to the database. {"timestamp":"2022-05-27T03:26:01.620Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-27T03:26:52.235Z"}
info: Connected to the database. {"timestamp":"2022-05-27T03:26:52.259Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-27T03:27:05.994Z"}
info: Connected to the database. {"timestamp":"2022-05-27T03:27:06.031Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-27T03:27:15.527Z"}
info: Connected to the database. {"timestamp":"2022-05-27T03:27:15.565Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-27T03:29:13.844Z"}
info: Connected to the database. {"timestamp":"2022-05-27T03:29:13.872Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-27T03:29:59.789Z"}
info: Connected to the database. {"timestamp":"2022-05-27T03:29:59.823Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-27T03:30:16.158Z"}
info: Connected to the database. {"timestamp":"2022-05-27T03:30:16.194Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-27T03:30:20.509Z"}
info: Connected to the database. {"timestamp":"2022-05-27T03:30:20.540Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-27T03:30:25.935Z"}
info: Connected to the database. {"timestamp":"2022-05-27T03:30:25.962Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-27T03:33:35.182Z"}
info: Connected to the database. {"timestamp":"2022-05-27T03:33:35.214Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-27T03:34:02.543Z"}
info: Connected to the database. {"timestamp":"2022-05-27T03:34:02.570Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-27T03:34:19.461Z"}
info: Connected to the database. {"timestamp":"2022-05-27T03:34:19.502Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-27T03:34:31.085Z"}
info: Connected to the database. {"timestamp":"2022-05-27T03:34:31.119Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-27T03:34:35.379Z"}
info: Connected to the database. {"timestamp":"2022-05-27T03:34:35.410Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-27T03:44:43.554Z"}
info: Connected to the database. {"timestamp":"2022-05-27T03:44:43.588Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-27T03:45:18.359Z"}
info: Connected to the database. {"timestamp":"2022-05-27T03:45:18.396Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-27T07:19:08.302Z"}
info: Connected to the database. {"timestamp":"2022-05-27T07:19:08.326Z"}
error: 
    status - 500 
    message - ValidationError: "password" is required 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2022-05-27T07:19:48.222Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-27T07:21:12.661Z"}
info: Connected to the database. {"timestamp":"2022-05-27T07:21:12.693Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-27T07:21:18.550Z"}
info: Connected to the database. {"timestamp":"2022-05-27T07:21:18.575Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-27T07:22:00.877Z"}
info: Connected to the database. {"timestamp":"2022-05-27T07:22:00.910Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-27T07:34:05.404Z"}
info: Connected to the database. {"timestamp":"2022-05-27T07:34:05.433Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-27T07:34:33.442Z"}
info: Connected to the database. {"timestamp":"2022-05-27T07:34:33.470Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-27T07:36:19.826Z"}
info: Connected to the database. {"timestamp":"2022-05-27T07:36:19.852Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-27T07:37:18.649Z"}
info: Connected to the database. {"timestamp":"2022-05-27T07:37:18.672Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-27T07:37:40.526Z"}
info: Connected to the database. {"timestamp":"2022-05-27T07:37:40.558Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-27T07:37:49.828Z"}
info: Connected to the database. {"timestamp":"2022-05-27T07:37:49.856Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-27T07:44:16.838Z"}
info: Connected to the database. {"timestamp":"2022-05-27T07:44:16.860Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-27T07:44:31.075Z"}
info: Connected to the database. {"timestamp":"2022-05-27T07:44:31.104Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-27T07:45:00.098Z"}
info: Connected to the database. {"timestamp":"2022-05-27T07:45:00.127Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-27T07:45:08.977Z"}
info: Connected to the database. {"timestamp":"2022-05-27T07:45:09.018Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-27T07:45:12.398Z"}
info: Connected to the database. {"timestamp":"2022-05-27T07:45:12.433Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-27T07:45:17.828Z"}
info: Connected to the database. {"timestamp":"2022-05-27T07:45:17.858Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-27T07:45:30.322Z"}
info: Connected to the database. {"timestamp":"2022-05-27T07:45:30.346Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-27T07:45:33.949Z"}
info: Connected to the database. {"timestamp":"2022-05-27T07:45:33.985Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-27T07:46:10.965Z"}
info: Connected to the database. {"timestamp":"2022-05-27T07:46:10.993Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-27T07:46:21.682Z"}
info: Connected to the database. {"timestamp":"2022-05-27T07:46:21.713Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-27T07:47:32.558Z"}
info: Connected to the database. {"timestamp":"2022-05-27T07:47:32.587Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-27T07:47:43.195Z"}
info: Connected to the database. {"timestamp":"2022-05-27T07:47:43.223Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-27T07:47:53.457Z"}
info: Connected to the database. {"timestamp":"2022-05-27T07:47:53.486Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-27T07:47:58.321Z"}
info: Connected to the database. {"timestamp":"2022-05-27T07:47:58.350Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-27T07:48:01.755Z"}
info: Connected to the database. {"timestamp":"2022-05-27T07:48:01.782Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-27T07:48:12.488Z"}
info: Connected to the database. {"timestamp":"2022-05-27T07:48:12.526Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-27T07:48:15.253Z"}
info: Connected to the database. {"timestamp":"2022-05-27T07:48:15.283Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-27T07:48:41.539Z"}
info: Connected to the database. {"timestamp":"2022-05-27T07:48:41.566Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-27T07:48:52.992Z"}
info: Connected to the database. {"timestamp":"2022-05-27T07:48:53.018Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-27T07:49:06.057Z"}
info: Connected to the database. {"timestamp":"2022-05-27T07:49:06.080Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-27T07:49:15.674Z"}
info: Connected to the database. {"timestamp":"2022-05-27T07:49:15.701Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-27T07:49:21.969Z"}
info: Connected to the database. {"timestamp":"2022-05-27T07:49:21.994Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-27T07:49:25.988Z"}
info: Connected to the database. {"timestamp":"2022-05-27T07:49:26.023Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-27T07:49:46.472Z"}
info: Connected to the database. {"timestamp":"2022-05-27T07:49:46.506Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-27T07:49:52.959Z"}
info: Connected to the database. {"timestamp":"2022-05-27T07:49:52.990Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-27T07:50:02.012Z"}
info: Connected to the database. {"timestamp":"2022-05-27T07:50:02.037Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-27T07:50:07.066Z"}
info: Connected to the database. {"timestamp":"2022-05-27T07:50:07.100Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-27T07:50:13.115Z"}
info: Connected to the database. {"timestamp":"2022-05-27T07:50:13.145Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-27T07:50:46.370Z"}
info: Connected to the database. {"timestamp":"2022-05-27T07:50:46.390Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-27T07:52:09.618Z"}
info: Connected to the database. {"timestamp":"2022-05-27T07:52:09.639Z"}
error: 
    status - 500 
    message - SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at parse (D:\projectt\fundo-notes\node_modules\body-parser\lib\types\json.js:89:19)
    at D:\projectt\fundo-notes\node_modules\body-parser\lib\read.js:128:18
    at AsyncResource.runInAsyncScope (node:async_hooks:201:9)
    at invokeCallback (D:\projectt\fundo-notes\node_modules\raw-body\index.js:231:16)
    at done (D:\projectt\fundo-notes\node_modules\raw-body\index.js:220:7)
    at IncomingMessage.onEnd (D:\projectt\fundo-notes\node_modules\raw-body\index.js:280:7)
    at IncomingMessage.emit (node:events:538:35)
    at IncomingMessage.emit (node:domain:475:12)
    at endReadableNT (node:internal/streams/readable:1345:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) 
    url - /api/v1/users 
    method - GET 
    IP - ::1
   {"timestamp":"2022-05-27T07:53:07.022Z"}
error: 
    status - 500 
    message - SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at parse (D:\projectt\fundo-notes\node_modules\body-parser\lib\types\json.js:89:19)
    at D:\projectt\fundo-notes\node_modules\body-parser\lib\read.js:128:18
    at AsyncResource.runInAsyncScope (node:async_hooks:201:9)
    at invokeCallback (D:\projectt\fundo-notes\node_modules\raw-body\index.js:231:16)
    at done (D:\projectt\fundo-notes\node_modules\raw-body\index.js:220:7)
    at IncomingMessage.onEnd (D:\projectt\fundo-notes\node_modules\raw-body\index.js:280:7)
    at IncomingMessage.emit (node:events:538:35)
    at IncomingMessage.emit (node:domain:475:12)
    at endReadableNT (node:internal/streams/readable:1345:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2022-05-27T07:53:17.652Z"}
error: 
    status - 500 
    message - ValidationError: "password" is required 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2022-05-27T07:53:33.604Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-27T07:56:30.244Z"}
info: Connected to the database. {"timestamp":"2022-05-27T07:56:30.273Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-27T07:56:41.570Z"}
info: Connected to the database. {"timestamp":"2022-05-27T07:56:41.605Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-27T07:56:45.019Z"}
info: Connected to the database. {"timestamp":"2022-05-27T07:56:45.049Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-27T07:56:48.877Z"}
info: Connected to the database. {"timestamp":"2022-05-27T07:56:48.953Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-27T07:56:52.341Z"}
info: Connected to the database. {"timestamp":"2022-05-27T07:56:52.371Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-27T07:57:07.319Z"}
info: Connected to the database. {"timestamp":"2022-05-27T07:57:07.346Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-27T07:57:11.971Z"}
info: Connected to the database. {"timestamp":"2022-05-27T07:57:12.000Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-27T07:57:17.664Z"}
info: Connected to the database. {"timestamp":"2022-05-27T07:57:17.693Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-27T07:57:54.063Z"}
info: Connected to the database. {"timestamp":"2022-05-27T07:57:54.096Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-27T07:58:18.191Z"}
info: Connected to the database. {"timestamp":"2022-05-27T07:58:18.216Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-27T07:58:25.204Z"}
info: Connected to the database. {"timestamp":"2022-05-27T07:58:25.235Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-27T07:58:32.376Z"}
info: Connected to the database. {"timestamp":"2022-05-27T07:58:32.411Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-27T07:58:37.566Z"}
info: Connected to the database. {"timestamp":"2022-05-27T07:58:37.597Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-27T07:58:45.072Z"}
info: Connected to the database. {"timestamp":"2022-05-27T07:58:45.093Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-27T11:32:40.048Z"}
info: Connected to the database. {"timestamp":"2022-05-27T11:32:40.070Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-28T00:52:59.952Z"}
info: Connected to the database. {"timestamp":"2022-05-28T00:52:59.985Z"}
error: 
    status - 500 
    message - ValidationError: "password" is required 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2022-05-28T00:56:05.456Z"}
error: 
    status - 500 
    message - ValidationError: "firstName" is not allowed 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2022-05-28T00:56:51.591Z"}
error: 
    status - 500 
    message - ValidationError: "firstName" is not allowed 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2022-05-28T00:57:55.240Z"}
error: 
    status - 500 
    message - ValidationError: "lastName" is not allowed 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2022-05-28T00:58:15.626Z"}
error: 
    status - 500 
    message - ValidationError: "password" is required 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2022-05-28T00:59:00.093Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-28T01:02:53.348Z"}
info: Connected to the database. {"timestamp":"2022-05-28T01:02:53.380Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-28T01:03:01.148Z"}
info: Connected to the database. {"timestamp":"2022-05-28T01:03:01.172Z"}
error: 
    status - 500 
    message - ValidationError: "password" is required 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2022-05-28T01:03:28.985Z"}
error: 
    status - 500 
    message - ValidationError: "firstName" is not allowed 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2022-05-28T01:04:47.900Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-28T01:05:16.760Z"}
info: Connected to the database. {"timestamp":"2022-05-28T01:05:16.785Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-28T01:05:27.569Z"}
info: Connected to the database. {"timestamp":"2022-05-28T01:05:27.600Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-28T01:05:33.581Z"}
info: Connected to the database. {"timestamp":"2022-05-28T01:05:33.607Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-28T01:05:56.027Z"}
info: Connected to the database. {"timestamp":"2022-05-28T01:05:56.051Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-28T01:07:18.742Z"}
info: Connected to the database. {"timestamp":"2022-05-28T01:07:18.770Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-28T01:07:43.015Z"}
info: Connected to the database. {"timestamp":"2022-05-28T01:07:43.041Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-28T01:08:32.714Z"}
info: Connected to the database. {"timestamp":"2022-05-28T01:08:32.740Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-28T02:32:44.510Z"}
info: Connected to the database. {"timestamp":"2022-05-28T02:32:44.543Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-28T02:33:10.211Z"}
info: Connected to the database. {"timestamp":"2022-05-28T02:33:10.246Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-28T02:33:13.951Z"}
info: Connected to the database. {"timestamp":"2022-05-28T02:33:13.976Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-28T02:33:52.990Z"}
info: Connected to the database. {"timestamp":"2022-05-28T02:33:53.018Z"}
error: 
      status - 11000
      message - E11000 duplicate key error collection: SampleDB_Adesh.users index: email_1 dup key: { email: "barbadeadesh@gmail.com" } 
      url - /api/v1/users 
      method - POST 
      IP - ::1
     {"timestamp":"2022-05-28T03:18:30.942Z"}
error: 
    status - 500 
    message - RangeError: Invalid status code: 11000
    at new NodeError (node:internal/errors:371:5)
    at ServerResponse.writeHead (node:_http_server:274:11)
    at ServerResponse.writeHead (D:\projectt\fundo-notes\node_modules\on-headers\index.js:44:26)
    at ServerResponse._implicitHeader (node:_http_server:265:8)
    at write_ (node:_http_outgoing:766:9)
    at ServerResponse.end (node:_http_outgoing:855:5)
    at ServerResponse.send (D:\projectt\fundo-notes\node_modules\express\lib\response.js:232:10)
    at ServerResponse.json (D:\projectt\fundo-notes\node_modules\express\lib\response.js:278:15)
    at appErrorHandler (D:\projectt\fundo-notes\src\middlewares\/error.middleware.js:36:26)
    at Layer.handle_error (D:\projectt\fundo-notes\node_modules\express\lib\router\layer.js:71:5)
    at trim_prefix (D:\projectt\fundo-notes\node_modules\express\lib\router\index.js:326:13)
    at D:\projectt\fundo-notes\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\projectt\fundo-notes\node_modules\express\lib\router\index.js:346:12)
    at Immediate.next (D:\projectt\fundo-notes\node_modules\express\lib\router\index.js:280:10)
    at Immediate._onImmediate (D:\projectt\fundo-notes\node_modules\express\lib\router\index.js:646:15)
    at processImmediate (node:internal/timers:468:21) 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2022-05-28T03:18:30.974Z"}
error: 
    status - 500 
    message - ValidationError: "firstName" is not allowed 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2022-05-28T03:20:10.765Z"}
error: 
    status - 500 
    message - ValidationError: "password" is required 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2022-05-28T03:22:58.947Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-28T03:23:41.699Z"}
info: Connected to the database. {"timestamp":"2022-05-28T03:23:41.730Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-28T03:23:49.481Z"}
info: Connected to the database. {"timestamp":"2022-05-28T03:23:49.518Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-28T03:27:25.156Z"}
info: Connected to the database. {"timestamp":"2022-05-28T03:27:25.189Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-28T03:32:51.541Z"}
info: Connected to the database. {"timestamp":"2022-05-28T03:32:51.564Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-28T03:34:10.259Z"}
info: Connected to the database. {"timestamp":"2022-05-28T03:34:10.285Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-28T03:34:22.142Z"}
info: Connected to the database. {"timestamp":"2022-05-28T03:34:22.172Z"}
error: 
    status - 500 
    message - TypeError: _user.default.findone is not a function
    at _callee3$ (D:\projectt\fundo-notes\src\services\/user.service.js:24:27)
    at tryCatch (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.userLogin (D:\projectt\fundo-notes\src\services\/user.service.js:23:23)
    at _callee3$ (D:\projectt\fundo-notes\src\controllers\/user.controller.js:49:36)
    at tryCatch (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2022-05-28T03:34:30.403Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-28T03:35:15.989Z"}
info: Connected to the database. {"timestamp":"2022-05-28T03:35:16.024Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-28T03:35:25.065Z"}
info: Connected to the database. {"timestamp":"2022-05-28T03:35:25.100Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-28T03:38:34.120Z"}
info: Connected to the database. {"timestamp":"2022-05-28T03:38:34.144Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-28T03:39:44.854Z"}
info: Connected to the database. {"timestamp":"2022-05-28T03:39:44.881Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-28T03:39:58.686Z"}
info: Connected to the database. {"timestamp":"2022-05-28T03:39:58.711Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-28T03:40:41.468Z"}
info: Connected to the database. {"timestamp":"2022-05-28T03:40:41.496Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-28T03:40:45.190Z"}
info: Connected to the database. {"timestamp":"2022-05-28T03:40:45.225Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-28T03:40:50.554Z"}
info: Connected to the database. {"timestamp":"2022-05-28T03:40:50.597Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-28T03:40:57.008Z"}
info: Connected to the database. {"timestamp":"2022-05-28T03:40:57.035Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-28T03:41:02.581Z"}
info: Connected to the database. {"timestamp":"2022-05-28T03:41:02.605Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-28T03:41:07.567Z"}
info: Connected to the database. {"timestamp":"2022-05-28T03:41:07.593Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-28T03:41:14.144Z"}
info: Connected to the database. {"timestamp":"2022-05-28T03:41:14.167Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-28T03:41:49.637Z"}
info: Connected to the database. {"timestamp":"2022-05-28T03:41:49.663Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-28T03:42:55.248Z"}
info: Connected to the database. {"timestamp":"2022-05-28T03:42:55.291Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-28T03:42:58.014Z"}
info: Connected to the database. {"timestamp":"2022-05-28T03:42:58.040Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-28T03:43:03.697Z"}
info: Connected to the database. {"timestamp":"2022-05-28T03:43:03.726Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-28T03:43:17.601Z"}
info: Connected to the database. {"timestamp":"2022-05-28T03:43:17.622Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-28T03:43:36.001Z"}
info: Connected to the database. {"timestamp":"2022-05-28T03:43:36.042Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-28T03:46:05.161Z"}
info: Connected to the database. {"timestamp":"2022-05-28T03:46:05.196Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-28T03:46:30.123Z"}
info: Connected to the database. {"timestamp":"2022-05-28T03:46:30.148Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-28T03:46:39.100Z"}
info: Connected to the database. {"timestamp":"2022-05-28T03:46:39.133Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-28T03:46:50.962Z"}
info: Connected to the database. {"timestamp":"2022-05-28T03:46:50.997Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-28T03:47:00.949Z"}
info: Connected to the database. {"timestamp":"2022-05-28T03:47:00.977Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-28T03:47:06.009Z"}
info: Connected to the database. {"timestamp":"2022-05-28T03:47:06.044Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-28T03:47:08.813Z"}
info: Connected to the database. {"timestamp":"2022-05-28T03:47:08.837Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-28T03:47:14.444Z"}
info: Connected to the database. {"timestamp":"2022-05-28T03:47:14.475Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-28T03:47:18.931Z"}
info: Connected to the database. {"timestamp":"2022-05-28T03:47:18.959Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-28T03:47:21.563Z"}
info: Connected to the database. {"timestamp":"2022-05-28T03:47:21.589Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-28T03:48:12.246Z"}
info: Connected to the database. {"timestamp":"2022-05-28T03:48:12.275Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-30T10:23:24.131Z"}
info: Connected to the database. {"timestamp":"2022-05-30T10:23:24.157Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-30T10:24:36.429Z"}
info: Connected to the database. {"timestamp":"2022-05-30T10:24:36.450Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-30T10:28:25.202Z"}
info: Connected to the database. {"timestamp":"2022-05-30T10:28:25.232Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-30T10:28:33.092Z"}
info: Connected to the database. {"timestamp":"2022-05-30T10:28:33.114Z"}
error: 
    status - 500 
    message - ReferenceError: error is not defined
    at _callee3$ (D:\projectt\fundo-notes\src\services\/user.service.js:23:26)
    at tryCatch (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2022-05-30T10:31:56.472Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-30T10:32:31.025Z"}
info: Connected to the database. {"timestamp":"2022-05-30T10:32:31.053Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-30T10:32:36.365Z"}
info: Connected to the database. {"timestamp":"2022-05-30T10:32:36.391Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-30T10:32:39.638Z"}
info: Connected to the database. {"timestamp":"2022-05-30T10:32:39.661Z"}
error: 
    status - 500 
    message - ReferenceError: error is not defined
    at _callee3$ (D:\projectt\fundo-notes\src\services\/user.service.js:23:26)
    at tryCatch (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2022-05-30T10:32:47.471Z"}
error: 
    status - 500 
    message - ReferenceError: error is not defined
    at _callee3$ (D:\projectt\fundo-notes\src\services\/user.service.js:23:26)
    at tryCatch (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2022-05-30T10:33:16.638Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-30T10:34:07.961Z"}
info: Connected to the database. {"timestamp":"2022-05-30T10:34:07.986Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-30T10:34:24.011Z"}
info: Connected to the database. {"timestamp":"2022-05-30T10:34:24.036Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-30T10:34:31.543Z"}
info: Connected to the database. {"timestamp":"2022-05-30T10:34:31.566Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-30T10:34:38.576Z"}
info: Connected to the database. {"timestamp":"2022-05-30T10:34:38.605Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-30T10:35:41.216Z"}
info: Connected to the database. {"timestamp":"2022-05-30T10:35:41.239Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-30T10:39:44.668Z"}
info: Connected to the database. {"timestamp":"2022-05-30T10:39:44.692Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-30T10:39:50.531Z"}
info: Connected to the database. {"timestamp":"2022-05-30T10:39:50.552Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-30T10:42:12.924Z"}
info: Connected to the database. {"timestamp":"2022-05-30T10:42:12.949Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-30T10:42:15.529Z"}
info: Connected to the database. {"timestamp":"2022-05-30T10:42:15.553Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-30T10:42:24.429Z"}
info: Connected to the database. {"timestamp":"2022-05-30T10:42:24.451Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-30T10:42:47.588Z"}
info: Connected to the database. {"timestamp":"2022-05-30T10:42:47.611Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-30T10:42:52.806Z"}
info: Connected to the database. {"timestamp":"2022-05-30T10:42:52.836Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-30T10:42:58.025Z"}
info: Connected to the database. {"timestamp":"2022-05-30T10:42:58.050Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-30T10:43:04.120Z"}
info: Connected to the database. {"timestamp":"2022-05-30T10:43:04.149Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-30T10:43:06.858Z"}
info: Connected to the database. {"timestamp":"2022-05-30T10:43:06.884Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-30T10:43:09.458Z"}
info: Connected to the database. {"timestamp":"2022-05-30T10:43:09.479Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-30T10:43:17.702Z"}
info: Connected to the database. {"timestamp":"2022-05-30T10:43:17.728Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-30T10:43:43.880Z"}
info: Connected to the database. {"timestamp":"2022-05-30T10:43:43.904Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-30T10:43:48.892Z"}
info: Connected to the database. {"timestamp":"2022-05-30T10:43:48.922Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-30T10:43:51.780Z"}
info: Connected to the database. {"timestamp":"2022-05-30T10:43:51.807Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-30T10:43:56.319Z"}
info: Connected to the database. {"timestamp":"2022-05-30T10:43:56.341Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-30T10:43:59.182Z"}
info: Connected to the database. {"timestamp":"2022-05-30T10:43:59.480Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-30T10:44:04.378Z"}
info: Connected to the database. {"timestamp":"2022-05-30T10:44:04.400Z"}
error: 
    status - 500 
    message - Error: user Exist
    at _callee3$ (D:\projectt\fundo-notes\src\services\/user.service.js:26:11)
    at tryCatch (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2022-05-30T10:44:25.384Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-30T10:44:42.195Z"}
info: Connected to the database. {"timestamp":"2022-05-30T10:44:42.219Z"}
error: 
    status - 500 
    message - Error: user Exist
    at _callee3$ (D:\projectt\fundo-notes\src\services\/user.service.js:26:11)
    at tryCatch (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2022-05-30T10:44:47.212Z"}
error: 
    status - 500 
    message - Error: user Exist
    at _callee3$ (D:\projectt\fundo-notes\src\services\/user.service.js:26:11)
    at tryCatch (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2022-05-30T10:44:48.805Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-30T10:45:21.713Z"}
info: Connected to the database. {"timestamp":"2022-05-30T10:45:21.735Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-30T10:46:16.716Z"}
info: Connected to the database. {"timestamp":"2022-05-30T10:46:16.743Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-30T10:46:21.720Z"}
info: Connected to the database. {"timestamp":"2022-05-30T10:46:21.747Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-30T10:48:56.474Z"}
info: Connected to the database. {"timestamp":"2022-05-30T10:48:56.501Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-30T10:49:03.177Z"}
info: Connected to the database. {"timestamp":"2022-05-30T10:49:03.199Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-30T10:53:05.472Z"}
info: Connected to the database. {"timestamp":"2022-05-30T10:53:05.496Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-30T10:53:08.245Z"}
info: Connected to the database. {"timestamp":"2022-05-30T10:53:08.271Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-30T10:53:51.973Z"}
info: Connected to the database. {"timestamp":"2022-05-30T10:53:51.996Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-30T10:56:50.158Z"}
info: Connected to the database. {"timestamp":"2022-05-30T10:56:50.184Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-30T11:17:42.128Z"}
info: Connected to the database. {"timestamp":"2022-05-30T11:17:42.151Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-30T11:17:45.611Z"}
info: Connected to the database. {"timestamp":"2022-05-30T11:17:45.646Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-30T11:17:48.012Z"}
info: Connected to the database. {"timestamp":"2022-05-30T11:17:48.036Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-30T11:18:00.697Z"}
info: Connected to the database. {"timestamp":"2022-05-30T11:18:00.720Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-30T11:18:12.131Z"}
info: Connected to the database. {"timestamp":"2022-05-30T11:18:12.155Z"}
error: 
    status - 500 
    message - TypeError: Cannot read properties of undefined (reading 'email')
    at _callee3$ (D:\projectt\fundo-notes\src\services\/user.service.js:24:49)
    at tryCatch (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.userLogin (D:\projectt\fundo-notes\src\services\/user.service.js:23:23)
    at _callee3$ (D:\projectt\fundo-notes\src\controllers\/user.controller.js:49:36)
    at tryCatch (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2022-05-30T11:18:27.453Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-30T11:18:45.656Z"}
info: Connected to the database. {"timestamp":"2022-05-30T11:18:45.678Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-30T11:19:26.054Z"}
info: Connected to the database. {"timestamp":"2022-05-30T11:19:26.118Z"}
error: 
    status - 500 
    message - ReferenceError: error is not defined
    at _callee3$ (D:\projectt\fundo-notes\src\services\/user.service.js:23:26)
    at tryCatch (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2022-05-30T11:19:30.220Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-30T11:20:54.391Z"}
info: Connected to the database. {"timestamp":"2022-05-30T11:20:54.417Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-30T11:21:05.290Z"}
info: Connected to the database. {"timestamp":"2022-05-30T11:21:05.311Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-30T11:21:42.138Z"}
info: Connected to the database. {"timestamp":"2022-05-30T11:21:42.168Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-30T11:22:11.575Z"}
info: Connected to the database. {"timestamp":"2022-05-30T11:22:11.601Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-30T11:23:00.993Z"}
info: Connected to the database. {"timestamp":"2022-05-30T11:23:01.024Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-30T11:23:06.218Z"}
info: Connected to the database. {"timestamp":"2022-05-30T11:23:06.243Z"}
error: 
    status - 500 
    message - ReferenceError: error is not defined
    at _callee3$ (D:\projectt\fundo-notes\src\services\/user.service.js:23:26)
    at tryCatch (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2022-05-30T11:26:07.552Z"}
error: 
    status - 500 
    message - ReferenceError: error is not defined
    at _callee3$ (D:\projectt\fundo-notes\src\services\/user.service.js:23:26)
    at tryCatch (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2022-05-30T11:26:14.179Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-30T11:26:30.899Z"}
info: Connected to the database. {"timestamp":"2022-05-30T11:26:30.919Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-30T11:26:45.854Z"}
info: Connected to the database. {"timestamp":"2022-05-30T11:26:45.880Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-30T11:29:42.852Z"}
info: Connected to the database. {"timestamp":"2022-05-30T11:29:42.876Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-30T11:41:39.278Z"}
info: Connected to the database. {"timestamp":"2022-05-30T11:41:39.306Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-30T11:41:43.306Z"}
info: Connected to the database. {"timestamp":"2022-05-30T11:41:43.339Z"}
error: 
    status - 500 
    message - ReferenceError: error is not defined
    at _callee3$ (D:\projectt\fundo-notes\src\services\/user.service.js:23:26)
    at tryCatch (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2022-05-30T11:43:52.981Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-30T11:44:32.925Z"}
info: Connected to the database. {"timestamp":"2022-05-30T11:44:32.956Z"}
